function tf = vf_structEvent(x)
% tf = vf_structEvent(x)
%
% tf     scalar logical
%
% validation function for field names of structure for event channel
% produced by Spike2

tf = false;

finamesE ={ 'title',...
    'comment',...
    'interval',...
    'start',...
    'length',...
    'values'};

finamesNotE ={'scale',...
    'offset',...
    'units',...
    'codes',...
    'resolution'};

if isstruct(x) && isscalar(x) &&...
        all(isfield(x, finamesE)) &&...
        all(~isfield(x, finamesNotE))
    
    if iscolumn(x.values)
        if islogical(x.values) || ...
                isnumeric(x.values) && (isempty(x.values) || all(x.values(x.values ~= 0) == 1))
            tf = true;
        end
    end
end



