function tf = vf_structMarker(x)
% tf = vf_structMarker(x)
%
% tf     scalar logical
%
% validation function for field names of structure for event channel
% produced by Spike2
tf = false;

finamesM ={'title',...
            'comment',...
            'resolution',...
            'length',...
            'times',...
            'codes'};
        
if isstruct(x) && isscalar(x) &&...
            all(isfield(x, finamesM)) &&...
            isa(x.codes, 'uint8')
    tf = true;
end